### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by deathwing573** [Vaiz/HsReconnectTool#1]

**Comment by Vaiz** [comment]
Well, you don't need to install this application, but I can make a manual for some extra steps.

1. Install .NET Framework 4.8.  [(download link)](https://dotnet.microsoft.com/download/dotnet-framework/net48)
2. Download latest release and unpack it. [(download link)](https://github.com/Vaiz/HsReconnectTool/releases)
3. Run HsReconnectTool.exe.
