### ISSUE TITLE
Game crashing after 21.3 patch

### ISSUE THREAD

**Issue by hsbgplayer** [Vaiz/HsReconnectTool#2]
After the latest update whenever i click "close connection", game crashes. I'm using Deck Tracker plugin. Not sure if you are still on this project but thanks in advance!

**Comment by Vaiz** [comment]
Hi, I confirmed the problem.
Try the new version: https://github.com/Vaiz/HsReconnectTool/releases/tag/v2.0
It works better but game still crashes sometimes.
